### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by FakeNameSE** [nok/sklearn-porter#17]
I am unable to install sklearn-porter for python3 through pip.

```
Collecting sklearn-porter
  Using cached sklearn-porter-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bdmsnkqx/sklearn-porter/setup.py", line 18, in <module>
        with open(requirements_path) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-bdmsnkqx/sklearn-porter/requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bdmsnkqx/sklearn-porter/
```

I am running python 3.6 on Arch Linux.

**Comment by nok** [comment]
Thanks @FakeNameSE, I will test and fix that issue.

**Comment by nok** [comment]
Hello @FakeNameSE,

okay, it should be fixed (https://github.com/nok/sklearn-porter/commit/2935828735fb1a8141c32f5f772172c12877c42d). You can upgrade the package with:

```
pip install --upgrade --force-reinstall
```

Thanks again for the hint!

Happy coding,
Darius

**Comment by FakeNameSE** [comment]
Thanks, it works!
