### ISSUE TITLE
Test code, which is part of the Readme is failing

### ISSUE THREAD

**Issue by HarvinderBhullar** [nok/sklearn-porter#71]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//miniconda3/envs/sklearn/lib/python3.7/site-packages/sklearn_porter/Porter.py", line 61, in __init__
    sklearn_ver = [int(v) for v in sklearn_ver]
  File "//miniconda3/envs/sklearn/lib/python3.7/site-packages/sklearn_porter/Porter.py", line 61, in <listcomp>
    sklearn_ver = [int(v) for v in sklearn_ver]
ValueError: invalid literal for int() with base 10: 'post1'

**Comment by HarvinderBhullar** [comment]
It is failing with latest release of scikit-learn.

**Comment by lucasavila00** [comment]
It's a bug in sklearn_porter.
Use another version of scikit_learn for now, 0.22.2.post1 is not compatible.
Use 0.22.2 or 0.22. They all work fine.
